---

- name: add celery worker start script
  template:
    src=./templates/celery_start.sh.j2
    dest=/srv/{{ host }}/celery_start.sh
  notify:
    - restart supervisor

- name: chmod celery worker start script
  file: path=/srv/{{ host }}/celery_start.sh owner=www-data group=www-data mode=0774

- name: add supervisor config
  template:
    src=./templates/supervisor_celery.conf.j2
    dest=/etc/supervisor/conf.d/{{ host }}_celery.conf
  notify:
    - restart supervisor