---

- name: removing default configuration p. 1
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - restart nginx

- name: removing default configuration p. 2
  file:
    path=/etc/nginx/sites-available/default
    state=absent
  notify:
    - restart nginx


- name: add nginx config to sites-available
  template:
    src={{ nginx_conf }}
    dest=/etc/nginx/sites-available/{{ host }}
  notify:
    - restart nginx

- name: add nginx config to sites-enabled
  file:
    src=/etc/nginx/sites-available/{{ host }}
    dest=/etc/nginx/sites-enabled/{{ host }}
    state=link
  notify:
    - restart nginx